kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mqcl1route 
  namespace: ibmmq 
spec:
  host: tls.chl.mq.ibm.com
  to:
    kind: Service
    name: mqcl1-ibm-mq 
  port:
    targetPort: 11414
  tls:
    termination: passthrough
