kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mqcl1route 
  namespace: mq 
spec:
  host: tlsone.chl.mq.ibm.com
  to:
    kind: Service
    name: mqcl1-ibm-mq 
  port:
    targetPort: 1414
  tls:
    termination: passthrough
