apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: mqcl1
  namespace: wbc9
spec:
  license:
    accept: true
    license: L-RJON-CD3JKX
    metric: VirtualProcessorCore
    use: NonProduction
  queueManager:
    storage:
      queueManager:
        enabled: true
    resources:
      limits:
        cpu: '0.3'
        memory: 1Gi
      requests:
        cpu: '0.3'
        memory: 1Gi
    availability:
     type: SingleInstance
#     type: NativeHA
    name: CL1
    mqsc:
    - configMap:
        name: cl1-mqsc
        items:
        - cl.mqsc
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
  version: 9.3.1.0-r1
  web:
    enabled: true
  pki:
    keys:
      - name: label1
        secret:
          secretName: mqcl1key
          items:
            - tls.key
            - tls.crt
  imagePullSecrets:
    - name: ibm-entitlement-key
